<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Common\Common.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Saves\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Saves\**" />
    </ItemGroup>

    <ItemGroup>
      <Content Remove="Saves\**" />
      <Content Remove="users.json" />
      <Content Remove="settings.json" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Saves\**" />
    </ItemGroup>

    <PropertyGroup Condition="'$(RuntimeIdentifier)' != ''">
        <_RuntimeOS>$([System.Text.RegularExpressions.Regex]::Match($(RuntimeIdentifier), '^([^-]+)'))</_RuntimeOS>
        <_RuntimeArch>$([System.Text.RegularExpressions.Regex]::Match($(RuntimeIdentifier), '([^-]+)$'))</_RuntimeArch>

        <_RuntimeOS Condition="'$(_RuntimeOS)' == 'win'">Windows</_RuntimeOS>
        <_RuntimeOS Condition="'$(_RuntimeOS)' == 'linux'">Linux</_RuntimeOS>

        <AssemblyName>$(MSBuildProjectName)-$(_RuntimeOS)-$(_RuntimeArch)</AssemblyName>
        <TargetName>$(MSBuildProjectName)-$(_RuntimeOS)-$(_RuntimeArch)</TargetName>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference 
                Include="..\Server.Generators\Server.Generators.csproj"
                OutputItemType="Analyzer"
                ReferenceOutputAssembly="false"
        />
    </ItemGroup>

</Project>
