<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Common\Common.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Saves\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Saves\**" />
    </ItemGroup>

    <ItemGroup>
      <Content Remove="Saves\**" />
      <Content Remove="users.json" />
      <Content Remove="settings.json" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Saves\**" />
    </ItemGroup>

    <Target Name="AppendTargetToAssemblyName" BeforeTargets="BeforeBuild" Condition="'$(RuntimeIdentifier)' != ''">
        <PropertyGroup>
            <_RuntimeOS>$(RuntimeIdentifier.Split('-')[0])</_RuntimeOS>
            <_RuntimeArch>$(RuntimeIdentifier.Split('-')[1])</_RuntimeArch>

            <_RuntimeOS Condition="'$(_RuntimeOS)' == 'win'">Windows</_RuntimeOS>
            <_RuntimeOS Condition="'$(_RuntimeOS)' == 'linux'">Linux</_RuntimeOS>

            <AssemblyName>$(AssemblyName)-$(_RuntimeOS)-$(_RuntimeArch)</AssemblyName>
        </PropertyGroup>
    </Target>

</Project>
