using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Server.Generators;

[Generator(LanguageNames.CSharp)]
public class MessageHandlerIncrementalGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, _) => GetTargetTypeIfMatch(ctx))
            .Where(static m => m is not null);
        
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());
        
        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) => Execute(source.Left, source.Right!, spc));
    }
    
    private static INamedTypeSymbol? GetTargetTypeIfMatch(GeneratorSyntaxContext ctx)
    {
        ClassDeclarationSyntax classDeclaration = (ClassDeclarationSyntax)ctx.Node;

        if (ctx.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol symbol || symbol.IsAbstract ||
            symbol.TypeKind == TypeKind.Interface) return null;

        // Walk up inheritance or interface tree to find MessageHandler
        INamedTypeSymbol? current = symbol;
        while (current != null)
        {
            if (current.Name == "MessageHandler" || current.AllInterfaces.Any(i => i.Name == "MessageHandler"))
                return symbol;
            current = current.BaseType;
        }

        return null;
    }

    private static void Execute(Compilation _, ImmutableArray<INamedTypeSymbol> types,
        SourceProductionContext context)
    {
        if (types.IsEmpty) return;

        StringBuilder sb = new StringBuilder();
        sb.AppendLine(
            """
            // <auto-generated />
            using System;

            namespace Server.MessageHandlers.V1;

            public static partial class MessageHandlerFactory
            {
                private static partial MessageHandler[] GetMessageHandlers()
                {
                    return new MessageHandler[]
                    {
            """);

        foreach (INamedTypeSymbol? type in types.Distinct(SymbolComparer.Instance))
        {
            sb.AppendLine($"            new {type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}(),");
        }

        sb.AppendLine(
            """
                    };
                }
            }
            """);
        
        context.AddSource("MessageHandlerFactory.g.cs", sb.ToString());

    }
}

internal class SymbolComparer : IEqualityComparer<INamedTypeSymbol>
{
    public static readonly SymbolComparer Instance = new();
    public bool Equals(INamedTypeSymbol? x, INamedTypeSymbol? y) => SymbolEqualityComparer.Default.Equals(x, y);
    public int GetHashCode(INamedTypeSymbol obj) => SymbolEqualityComparer.Default.GetHashCode(obj);
}